#!/usr/bin/env bash
#==============================================================================
# Reusable HouseMember initialization helpers.
#==============================================================================

[[ -n "${HOUSE_MEMBER_LOADED:-}" ]] && return
HOUSE_MEMBER_LOADED=1

HOUSE_MEMBER_ERROR=""
HOUSE_MEMBER_ID=""

house_member_reject() {
    HOUSE_MEMBER_ERROR="$1"
    return 2
}

house_member_create() {
    local raw_member_id="$1"
    local display_name
    local member_id
    local member_uuid
    local members_dir
    local member_dir

    HOUSE_MEMBER_ERROR=""
    HOUSE_MEMBER_ID=""

    display_name="$(printf '%s' "$raw_member_id" |
        sed 's/^[[:space:]]*//; s/[[:space:]]*$//')"

    if [[ -z "$display_name" ]]; then
        house_member_reject "Member ID is required."
        return
    fi
    if [[ "$display_name" == *[[:space:]]* ]]; then
        house_member_reject "Member ID cannot contain spaces."
        return
    fi

    if [[ ! "$display_name" =~ ^[A-Za-z0-9][A-Za-z0-9._-]*$ ]]; then
        house_member_reject \
            "Member ID contains illegal filesystem characters."
        return
    fi

    member_id="${display_name,,}"
    members_dir="$(house_members_dir)" || {
        house_member_reject "Unable to locate the members directory."
        return
    }
    member_dir="${members_dir}/${member_id}"

    if [[ -e "$member_dir" ]]; then
        house_member_reject "Member '${member_id}' already exists."
        return
    fi

    if ! command -v uuidgen >/dev/null 2>&1; then
        house_member_reject "uuidgen is required to create a member."
        return
    fi
    if ! member_uuid="$(uuidgen)"; then
        house_member_reject "Unable to generate a member UUID."
        return
    fi

    if ! mkdir -p -- "$members_dir"; then
        house_member_reject "Unable to create the members directory."
        return
    fi
    if ! mkdir -- "$member_dir"; then
        if [[ -e "$member_dir" ]]; then
            house_member_reject "Member '${member_id}' already exists."
        else
            house_member_reject "Unable to create member '${member_id}'."
        fi
        return
    fi

    if ! mkdir -p -- \
            "$member_dir/assets" \
            "$member_dir/documents" \
            "$member_dir/photos" \
            "$member_dir/signatures" \
            "$member_dir/social"; then
        house_member_reject "Unable to create assets for member '${member_id}'."
        return
    fi

    if ! printf '%s\n' \
        'version: 1' \
        '' \
        'member:' \
        "  id: ${member_id}" \
        "  uuid: ${member_uuid}" \
        "  display_name: ${display_name}" \
        '' \
        'status:' \
        '  active: true' \
        '' \
        'contact:' \
        '  email:' \
        '  phone:' \
        '' \
        'branding:' \
        '  logo:' \
        '  primary_color:' \
        '' \
        'notes: |' \
        '' \
        'created:' \
        '  created_by: HouseToolkit' \
        '  created_date:' > "$member_dir/profile.yml"; then
        house_member_reject "Unable to write member '${member_id}' metadata."
        return
    fi

    if ! printf '%s\n' \
        "# ${display_name}" \
        '' \
        'HouseToolkit Member' \
        '' \
        'This directory contains all assets and metadata for this member.' \
        '' \
        'Generated by HouseToolkit.' > "$member_dir/README.md"; then
        house_member_reject "Unable to write member '${member_id}' README."
        return
    fi

    HOUSE_MEMBER_ID="$member_id"
}
