#!/usr/bin/env bash
#==============================================================================
# HouseCard profile metadata and schema helpers.
#==============================================================================

[[ -n "${HOUSE_CARD_LOADED:-}" ]] && return
HOUSE_CARD_LOADED=1

housecard_profile_member_value() {
    local profile_path="$1"
    local key="$2"

    awk -v key="$key" '
        $0 == "member:" {
            in_member = 1
            next
        }
        in_member && /^[^[:space:]#]/ {
            exit
        }
        in_member && $0 ~ "^  " key ":[[:space:]]*" {
            sub("^  " key ":[[:space:]]*", "")
            sub(/[[:space:]]+$/, "")
            print
            exit
        }
    ' "$profile_path"
}

housecard_write_card() {
    local card_path="$1"
    local member_id="$2"
    local member_uuid="$3"
    local display_name="$4"

    printf '%s\n' \
        'version: 1' \
        '' \
        'member:' \
        "  id: ${member_id}" \
        "  uuid: ${member_uuid}" \
        "  display_name: ${display_name}" \
        '' \
        'organization:' \
        '  name:' \
        '  department:' \
        '  title:' \
        '' \
        'contact:' \
        '  email:' \
        '  phone:' \
        '  website:' \
        '' \
        'branding:' \
        '  logo:' \
        '  primary_color:' \
        '  secondary_color:' \
        '  font:' \
        '' \
        'layout:' \
        '  template: standard' \
        '  orientation: landscape' \
        '' \
        'output:' \
        '  svg:' \
        '  pdf:' \
        '  png:' \
        '' \
        'status:' \
        '  initialized: true' > "$card_path"
}

housecard_write_readme() {
    local readme_path="$1"

    printf '%s\n' \
        '# HouseCard' \
        '' \
        'This directory contains the HouseCard metadata for this member.' \
        '' \
        'Generated by HouseToolkit.' \
        '' \
        'HouseToolkit does not currently render this metadata.' > "$readme_path"
}
